[package]
name = "todo-api"
version = "0.0.1"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
axum = "0.7.9"
chrono = { version = "0.4.39", features = ["serde"] }
deadpool-postgres = "0.14.1"
dotenvy = "0.15.7"
postgres-types = { version = "0.2.8", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
tokio-postgres = { version = "0.7.12", features = ["with-chrono-0_4", "with-serde_json-1", "with-uuid-1"] }
tower = "0.5.2"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
