name: Deploy to backend to personal server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'backend/src/**'
      - 'backend/Cargo.toml'
      - 'backend/Cargo.lock'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build app
      run: cargo build --bin todo-api --release

    - name: Test app
      run: cargo test --bin todo-api --release --verbose

    - name: Upload binary
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        source: backend/target/release/todo-api
        target: /tmp/todo-api/
        strip_components: 3

    - name: Setup server binary and restart
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        script: |
          sudo systemctl stop clearlist-api.service
          cp /tmp/todo-api/todo-api ${{ secrets.DEPLOY_PATH }}
          sudo systemctl restart clearlist-api.service
