name: Deploy to backend to personal server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'backend/src/**'
      - 'backend/Cargo.toml'
      - 'backend/Cargo.lock'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build app
      run: cargo build --bin todo-api --release

    - name: Test app
      run: cargo test --bin todo-api --verbose

    - name: Upload binary to proxy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PROXY_HOST }}
        username: ${{ secrets.PROXY_USER }}
        key: ${{ secrets.PROXY_KEY }}
        source: backend/target/release/todo-api
        target: /tmp/todo-api

    - name: Forward binary to server and restart service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROXY_HOST }}
        username: ${{ secrets.PROXY_USER }}
        key: ${{ secrets.PROXY_KEY }}
        script: |
          scp /tmp/todo-api ${{ secrets.MAIN_USER }}@${{ secrets.MAIN_HOST }}:${{ secrets.DEPLOY_PATH }}

          ssh ${{ secrets.MAIN_USER }}@${{ secrets.MAIN_HOST }} << 'EOF'
            sudo systemctl restart clearlist-api.service
          EOF
