name: Deploy to backend to personal server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'backend/src/**'
      - 'backend/Cargo.toml'
      - 'backend/Cargo.lock'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Test app
      run: cargo test --verbose

    - name: Build app
      run: cargo build --bin todo-api --release

    - name: Copy binary to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: backend/target/release/todo-api
        target: ${{ secrets.DEPLOY_PATH }}
        strip_components: 3

    - name: Restart systemd service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: sudo systemctl restart clearlist-server.service
